# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: wonderlamp.proto
# Protobuf Python Version: 6.30.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    0,
    '',
    'wonderlamp.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10wonderlamp.proto\x12\nwonderlamp\"\x1c\n\x04Vec2\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\"3\n\x05\x43olor\x12\t\n\x01r\x18\x01 \x01(\x02\x12\t\n\x01g\x18\x02 \x01(\x02\x12\t\n\x01\x62\x18\x03 \x01(\x02\x12\t\n\x01\x61\x18\x04 \x01(\x02\"n\n\nCreateRect\x12 \n\x06\x63\x65nter\x18\x01 \x01(\x0b\x32\x10.wonderlamp.Vec2\x12\r\n\x05width\x18\x02 \x01(\x02\x12\x0e\n\x06height\x18\x03 \x01(\x02\x12\x1f\n\x04\x66ill\x18\x04 \x01(\x0b\x32\x11.wonderlamp.Color\"a\n\x0c\x43reateCircle\x12 \n\x06\x63\x65nter\x18\x01 \x01(\x0b\x32\x10.wonderlamp.Vec2\x12\x0e\n\x06radius\x18\x02 \x01(\x02\x12\x1f\n\x04\x66ill\x18\x03 \x01(\x0b\x32\x11.wonderlamp.Color\"\x1d\n\nSetEnabled\x12\x0f\n\x07\x65nabled\x18\x01 \x01(\x08\"\x08\n\x06\x44\x65lete\"\xd8\x01\n\x07Request\x12\x0e\n\x06handle\x18\x01 \x01(\r\x12-\n\x0b\x63reate_rect\x18\n \x01(\x0b\x32\x16.wonderlamp.CreateRectH\x00\x12-\n\x0bset_enabled\x18\x0b \x01(\x0b\x32\x16.wonderlamp.SetEnabledH\x00\x12$\n\x06\x64\x65lete\x18\x0c \x01(\x0b\x32\x12.wonderlamp.DeleteH\x00\x12\x31\n\rcreate_circle\x18\r \x01(\x0b\x32\x18.wonderlamp.CreateCircleH\x00\x42\x06\n\x04\x62ody\")\n\x08Response\x12\x0e\n\x06handle\x18\x01 \x01(\x05\x12\r\n\x05\x65rror\x18\x02 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'wonderlamp_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_VEC2']._serialized_start=32
  _globals['_VEC2']._serialized_end=60
  _globals['_COLOR']._serialized_start=62
  _globals['_COLOR']._serialized_end=113
  _globals['_CREATERECT']._serialized_start=115
  _globals['_CREATERECT']._serialized_end=225
  _globals['_CREATECIRCLE']._serialized_start=227
  _globals['_CREATECIRCLE']._serialized_end=324
  _globals['_SETENABLED']._serialized_start=326
  _globals['_SETENABLED']._serialized_end=355
  _globals['_DELETE']._serialized_start=357
  _globals['_DELETE']._serialized_end=365
  _globals['_REQUEST']._serialized_start=368
  _globals['_REQUEST']._serialized_end=584
  _globals['_RESPONSE']._serialized_start=586
  _globals['_RESPONSE']._serialized_end=627
# @@protoc_insertion_point(module_scope)
